on: [issue_comment]

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          script: |-
            octokit.rest.actions.reRunWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: "822068640",
            });

#                workflow_id: 'assign.yml',
#console.log(context)
#if context.eventName == "issue_comment" {
#    core.setFailed('Action failed')
#}
#const result = await github.pulls.listReviews({
#    owner: "gravitational",
#    repo: "gh-actions-poc",
#    pull_number: context.payload.pull_request.number,
#})
#console.log(result)
#core.setFailed('Action failed')
