on: pull_request
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            console.log(context)
            octokit.rest.pulls.requestReviewers({
              owner: "gravitational",
              repo: "teleport",
              pull_number: context.pull_request.number,
              reviewers: [
                "r0mant"
              ]
            });
