# Workflow will trigger on all pull request review event types, on commit push to a 
# pull request (synchronize) event type
# 
# NOTE: Due to the sensitive nature of this workflow, it must always be run
# against master AND with minimal permissions. These properties must always
# be maintained!
name: Check
on: 
  pull_request_review:
    type: [submitted, edited, dismissed]

  pull_request_target: 
    types: [assigned, opened, reopened, ready_for_review, synchronize]

jobs: 
  check-reviews:
    name: Checking reviewers 
    # if: ${{ github.event.pull_request.head.repo.full_name == 'gravitational/gh-actions-poc' }}
    runs-on: ubuntu-latest
    steps:
      - name: Event name 
        run: echo ${{ github.event_name}}
      # Checkout master branch of Teleport repository. This is to prevent an
      # attacker from submitting their own review assignment logic. 
      - name: Checkout master branch 
        uses: actions/checkout@v2
        with:
          ref: dev-workflow-automation-testing 
      - name: Installing the latest version of Go.
        uses: actions/setup-go@v2
        # Run "check-reviewers" subcommand on bot.
      - name: Checking reviewers
        run: cd tool/ci && go run cmd/bot.go --token=${{ secrets.GITHUB_TOKEN }} --reviewers="{\"\":[\"quinqu\"], \"quinqu\":[\"0xblush\"]}" check-reviewers
