name: Dismiss Stale Workflows Runs
on:
  schedule:
    # Runs every 5 minutes
    - cron:  '* * * * *' 
permissions: 
  actions: write 
  pull-requests: read
  
jobs: 
  dismiss-stale-runs:
    name: Dismiss Stale Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Event name 
        run: echo ${{ github.event_name}}
      - name: Checkout master branch 
        uses: actions/checkout@v2
        with:
          ref: dev-workflow
      - name: Installing the latest version of Go.
        uses: actions/setup-go@v2
        # Run "check-reviewers" subcommand on bot.
      - name: Dismiss
        run: cd .github/workflows/ci && go run cmd/main.go --token=${{ secrets.GITHUB_TOKEN }} dismiss-runs
