on: [pull_request]

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.4'
      - run: go get -u github.com/google/go-github/v35
      - run: cd .github/workflows && go run hello.go
        env:
          TOKEN_AAA: ${{ secrets.GITHUB_TOKEN }}
